// ブランドマッチング v1 の型定義（Step1：型のみ・無挙動変更）。
//
// 目的: 写真分析/診断で得た世界観の軸（色・シルエット・ジャンル・年代…）を、
//   決定的（非AI）に近いブランド候補へ橋渡しするための辞書スキーマ。
//   v1 のマッチは 色 / シルエット / ジャンル / 年代 を主軸にする。
//
// ⚠️ 語彙ドリフト防止の方針:
//   genre/culture/color/silhouette/material 系のフィールドには、必ず
//   lib/style-taxonomy.ts の STYLE_AXES に存在するタグ「名」を入れる。
//   ここでズレると検索/マッチが静かに当たらなくなる。
//
//   型での厳密強制（リテラル union）は今回見送る。理由:
//   STYLE_AXES は `StyleAxis[]`（tags は `StyleTag[]`／name: string）で、
//   `as const` ではないため TypeScript からタグ名のリテラル union を導出できない。
//   厳密化するには style-taxonomy.ts 側を `as const`＋union export に改修する必要があり、
//   今回の「STYLE_AXES 無改修」制約に反する。ローカルでタグ名を再列挙するのは
//   ドリフトの温床になるので採らない。
//   → よって「軸別の型エイリアス（実体は string）＋出典軸コメント」で意図を固定し、
//      逸脱は後段（Step で追加する）テストで STYLE_AXES と突き合わせて検出する。

// ── 軸別タグ型（実体は string・出典は STYLE_AXES の対応する key）──
// いずれも STYLE_AXES に実在するタグ名のみを入れること（test で逸脱検出予定）。
export type GenreTag = string; // STYLE_AXES key="genre"
export type CultureTag = string; // STYLE_AXES key="culture"
export type ColorTag = string; // STYLE_AXES key="color"
export type SilhouetteTag = string; // STYLE_AXES key="silhouette"
export type MaterialTag = string; // STYLE_AXES key="material"
export type EraTag = string; // STYLE_AXES key="era"

export type BrandPriceTier = "low" | "mid" | "high" | "luxury";

export interface BrandTaxonomyEntry {
  /** ブランド名（表示・検索の主キー的識別子） */
  name: string;
  /** 自由記述のスタイルタグ（STYLE_AXES 縛りなし・ニュアンス補助） */
  styleTags: string[];
  /** STYLE_AXES key="genre" のタグ名 */
  genreCandidates: GenreTag[];
  /** STYLE_AXES key="culture" のタグ名 */
  cultureCandidates: CultureTag[];
  /** 得意なアイテム種別（自由記述・例: アウター/レザー/ニット） */
  itemStrengths: string[];
  /** STYLE_AXES key="material" のタグ名 */
  materialSignals: MaterialTag[];
  /** STYLE_AXES key="color" のタグ名 */
  colorSignals: ColorTag[];
  /** STYLE_AXES key="silhouette" のタグ名 */
  silhouetteSignals: SilhouetteTag[];
  /** STYLE_AXES key="era" のタグ名（写真から参照されやすい年代感・ブランド創業年ではない） */
  eraSignals: EraTag[];
  /** 価格帯 */
  priceTier: BrandPriceTier;
  /** 商品検索（楽天/ZOZO 等）に流す検索ワード候補 */
  searchKeywords: string[];
}

// 黒/モード/ミニマル/ストリート系の最初の 5 件（すべて STYLE_AXES 実在タグで構成）。
// 本格 seed（15〜30 件）は後続で追加。matcher・brand-learn 接続は Step3/4。
export const BRAND_TAXONOMY: BrandTaxonomyEntry[] = [
  {
    name: "Yohji Yamamoto",
    styleTags: ["黒一色", "ドレープ", "アヴァンギャルド", "ロング丈"],
    genreCandidates: ["モード", "ダーク/ブラックモード", "アヴァンギャルド/脱構築"],
    cultureCandidates: ["アーティスト/クリエイター", "パリ", "東京/原宿"],
    itemStrengths: ["ロングコート", "テーラードジャケット", "ワイドパンツ"],
    materialSignals: ["ウール", "コットン", "レザー"],
    colorSignals: ["オールブラック", "モノトーン", "ダークトーン"],
    silhouetteSignals: ["ドレープ", "ワイド", "オーバーサイズ", "Iライン"],
    eraSignals: ["1980s", "1990s"],
    priceTier: "luxury",
    searchKeywords: ["Yohji Yamamoto", "ヨウジヤマモト", "黒 モード コート", "Yohji Yamamoto wide pants"],
  },
  {
    name: "COMME des GARÇONS",
    styleTags: ["脱構築", "黒基調", "前衛的", "ボックスシルエット"],
    genreCandidates: ["アヴァンギャルド/脱構築", "モード", "ダーク/ブラックモード"],
    cultureCandidates: ["東京/原宿", "アーティスト/クリエイター", "パリ"],
    itemStrengths: ["変形ジャケット", "ニット", "アウター"],
    materialSignals: ["ウール", "コットン", "ナイロン"],
    colorSignals: ["オールブラック", "モノトーン", "ダークトーン"],
    silhouetteSignals: ["ボックス", "オーバーサイズ", "ドレープ"],
    eraSignals: ["1980s", "1990s"],
    priceTier: "luxury",
    searchKeywords: ["COMME des GARCONS", "コムデギャルソン", "黒 モード", "COMME des GARCONS jacket"],
  },
  {
    name: "stein",
    styleTags: ["ミニマルモード", "低彩度", "クリーン", "ワイドシルエット"],
    genreCandidates: ["ミニマルモード", "モード", "ミニマル"],
    cultureCandidates: ["中目黒/青山", "アーティスト/クリエイター", "編集者/スタイリスト"],
    itemStrengths: ["スラックス", "シャツ", "コート"],
    materialSignals: ["ウール", "コットン", "ナイロン"],
    colorSignals: ["モノトーン", "低彩度", "ニュートラル"],
    silhouetteSignals: ["ワイド", "ドレープ", "オーバーサイズ", "Iライン"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "high",
    searchKeywords: ["stein", "シュタイン", "stein coat", "stein wide pants", "ミニマル モード"],
  },
  {
    name: "COMOLI",
    styleTags: ["上質ベーシック", "ニュートラル", "力の抜けたきれいめ", "ナチュラル"],
    genreCandidates: ["ミニマル", "エフォートレス", "ノームコア"],
    cultureCandidates: ["中目黒/青山", "編集者/スタイリスト", "モデル私服(オフデューティ)"],
    itemStrengths: ["シャツ", "スラックス", "アウター"],
    materialSignals: ["コットン", "ウール", "リネン"],
    colorSignals: ["ニュートラル", "低彩度", "アースカラー", "ネイビー基調"],
    silhouetteSignals: ["ワイド", "オーバーサイズ", "ドレープ", "Iライン"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "high",
    searchKeywords: ["COMOLI", "コモリ", "COMOLI shirt", "COMOLI pants", "ミニマル きれいめ"],
  },
  {
    name: "LIDNM",
    styleTags: ["黒ベース", "きれいめストリート", "モノトーン", "ワイド"],
    genreCandidates: ["ミニマルストリート", "ブラックストリート", "ミニマル"],
    cultureCandidates: ["東京/原宿", "モデル私服(オフデューティ)", "編集者/スタイリスト"],
    itemStrengths: ["セットアップ", "アウター", "スラックス"],
    materialSignals: ["ウール", "ナイロン", "コットン"],
    colorSignals: ["オールブラック", "モノトーン", "低彩度"],
    silhouetteSignals: ["ワイド", "オーバーサイズ", "Iライン"],
    eraSignals: ["2020s"],
    priceTier: "mid",
    searchKeywords: ["LIDNM", "リドム", "黒 ストリート きれいめ", "LIDNM wide pants"],
  },
  {
    name: "Rick Owens",
    styleTags: ["黒一色", "ドレープ", "ダーク", "アヴァンギャルド"],
    genreCandidates: ["ダーク/ブラックモード", "アヴァンギャルド/脱構築", "モード"],
    cultureCandidates: ["アーティスト/クリエイター", "パリ"],
    itemStrengths: ["レザージャケット", "ロングカットソー", "ブーツ"],
    materialSignals: ["レザー", "コットン", "ウール"],
    colorSignals: ["オールブラック", "ダークトーン", "モノトーン"],
    silhouetteSignals: ["ドレープ", "レイヤード", "Iライン"],
    eraSignals: ["2000s", "2010s"],
    priceTier: "luxury",
    searchKeywords: ["Rick Owens", "リックオウエンス", "Rick Owens leather", "黒 ダーク モード"],
  },
  {
    name: "Maison Margiela",
    styleTags: ["脱構築", "中性的", "アーティスティック", "モード"],
    genreCandidates: ["アヴァンギャルド/脱構築", "モード", "ジェンダーレスモード"],
    cultureCandidates: ["パリ", "アーティスト/クリエイター", "編集者/スタイリスト"],
    itemStrengths: ["テーラードジャケット", "コート", "ニット"],
    materialSignals: ["ウール", "レザー", "コットン"],
    colorSignals: ["モノトーン", "ニュートラル", "低彩度"],
    silhouetteSignals: ["オーバーサイズ", "ドレープ", "ボックス"],
    eraSignals: ["1990s", "2000s"],
    priceTier: "luxury",
    searchKeywords: ["Maison Margiela", "メゾンマルジェラ", "Margiela", "脱構築 モード"],
  },
  {
    name: "AURALEE",
    styleTags: ["上質素材", "ニュートラル", "クリーン", "きれいめ"],
    genreCandidates: ["ミニマル", "エフォートレス", "ノームコア"],
    cultureCandidates: ["中目黒/青山", "編集者/スタイリスト", "モデル私服(オフデューティ)"],
    itemStrengths: ["ニット", "シャツ", "コート"],
    materialSignals: ["ウール", "コットン", "ニット"],
    colorSignals: ["ニュートラル", "低彩度", "ベージュ系"],
    silhouetteSignals: ["ワイド", "Iライン", "オーバーサイズ"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "high",
    searchKeywords: ["AURALEE", "オーラリー", "AURALEE knit", "AURALEE coat", "上質 ミニマル"],
  },
  {
    name: "Graphpaper",
    styleTags: ["ミニマル", "モノトーン", "モダンベーシック", "クリーン"],
    genreCandidates: ["ミニマル", "ミニマルモード", "エフォートレス"],
    cultureCandidates: ["中目黒/青山", "編集者/スタイリスト", "アーティスト/クリエイター"],
    itemStrengths: ["シャツ", "スラックス", "アウター"],
    materialSignals: ["コットン", "ウール", "ナイロン"],
    colorSignals: ["モノトーン", "低彩度", "ニュートラル"],
    silhouetteSignals: ["ワイド", "オーバーサイズ", "Iライン"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "high",
    searchKeywords: ["Graphpaper", "グラフペーパー", "Graphpaper shirt", "ミニマル モード"],
  },
  {
    name: "ATON",
    styleTags: ["上質ベーシック", "ニュートラル", "ナチュラル", "クリーン"],
    genreCandidates: ["ミニマル", "エフォートレス", "ノームコア"],
    cultureCandidates: ["中目黒/青山", "モデル私服(オフデューティ)", "編集者/スタイリスト"],
    itemStrengths: ["ニット", "カットソー", "スラックス"],
    materialSignals: ["コットン", "ウール", "ニット"],
    colorSignals: ["ニュートラル", "低彩度", "ベージュ系"],
    silhouetteSignals: ["ワイド", "Iライン", "オーバーサイズ"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "high",
    searchKeywords: ["ATON", "エイトン", "ATON knit", "上質 ベーシック"],
  },
  {
    name: "Lemaire",
    styleTags: ["フレンチミニマル", "ニュートラル", "ドレープ", "力の抜けた"],
    genreCandidates: ["ミニマル", "エフォートレス", "ミニマルモード"],
    cultureCandidates: ["パリ", "編集者/スタイリスト", "モデル私服(オフデューティ)"],
    itemStrengths: ["コート", "シャツ", "バッグ"],
    materialSignals: ["ウール", "コットン", "レザー"],
    colorSignals: ["ニュートラル", "ベージュ系", "低彩度"],
    silhouetteSignals: ["ドレープ", "ワイド", "Iライン"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "luxury",
    searchKeywords: ["Lemaire", "ルメール", "Lemaire coat", "フレンチ ミニマル"],
  },
  {
    name: "Our Legacy",
    styleTags: ["北欧モダン", "ニュートラル", "アーティスティック", "きれいめ"],
    genreCandidates: ["ミニマルモード", "モード", "エフォートレス"],
    cultureCandidates: ["編集者/スタイリスト", "アーティスト/クリエイター", "モデル私服(オフデューティ)"],
    itemStrengths: ["シャツ", "アウター", "ニット"],
    materialSignals: ["コットン", "ウール", "レザー"],
    colorSignals: ["低彩度", "ニュートラル", "アースカラー"],
    silhouetteSignals: ["ワイド", "オーバーサイズ", "ボックス"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "high",
    searchKeywords: ["Our Legacy", "アワーレガシー", "Our Legacy shirt", "北欧 モード"],
  },
  {
    name: "ADER ERROR",
    styleTags: ["韓国ストリート", "オーバーサイズ", "モノトーン", "差し色"],
    genreCandidates: ["韓国ストリート", "ミニマルストリート", "ストリート"],
    cultureCandidates: ["ソウル/弘大/江南", "K-POP私服/空港"],
    itemStrengths: ["スウェット", "アウター", "ニット"],
    materialSignals: ["コットン", "ナイロン", "ウール"],
    colorSignals: ["モノトーン", "低彩度", "差し色アクセント"],
    silhouetteSignals: ["オーバーサイズ", "ワイド", "ボックス"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "high",
    searchKeywords: ["ADER ERROR", "アーダーエラー", "ADER", "韓国 ストリート"],
  },
  {
    name: "thisisneverthat",
    styleTags: ["韓国ストリート", "ロゴグラフィック", "カジュアル", "オーバーサイズ"],
    genreCandidates: ["韓国ストリート", "ストリート", "スポーツストリート"],
    cultureCandidates: ["ソウル/弘大/江南", "K-POP私服/空港", "スケーター"],
    itemStrengths: ["パーカー", "スウェット", "ナイロンジャケット"],
    materialSignals: ["コットン", "ナイロン", "フリース"],
    colorSignals: ["モノトーン", "アースカラー", "差し色アクセント"],
    silhouetteSignals: ["オーバーサイズ", "ワイド", "ボックス"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["thisisneverthat", "ディスイズネバーザット", "韓国 ストリート", "thisisneverthat hoodie"],
  },
  {
    name: "UNDERCOVER",
    styleTags: ["裏原モード", "ダーク", "コンセプチュアル", "パンク"],
    genreCandidates: ["裏原系", "パンク", "モード"],
    cultureCandidates: ["東京/原宿", "パンク/ロック", "アーティスト/クリエイター"],
    itemStrengths: ["アウター", "カットソー", "ニット"],
    materialSignals: ["コットン", "ウール", "レザー"],
    colorSignals: ["モノトーン", "ダークトーン", "オールブラック"],
    silhouetteSignals: ["レイヤード", "オーバーサイズ", "Iライン"],
    eraSignals: ["1990s", "2000s"],
    priceTier: "high",
    searchKeywords: ["UNDERCOVER", "アンダーカバー", "UNDERCOVER jacket", "モード パンク"],
  },
  {
    name: "and wander",
    styleTags: ["日本アウトドア", "テック", "機能的", "ミニマル"],
    genreCandidates: ["ゴープコア", "アウトドア", "アーバンアウトドア"],
    cultureCandidates: ["登山家/アウトドア"],
    itemStrengths: ["シェル/マウンテンパーカー", "フリース", "バックパック"],
    materialSignals: ["ナイロン", "フリース", "化繊光沢"],
    colorSignals: ["低彩度", "アースカラー", "ニュートラル"],
    silhouetteSignals: ["ワイド", "オーバーサイズ", "レイヤード"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "high",
    searchKeywords: ["and wander", "アンドワンダー", "and wander jacket", "ゴープコア"],
  },
  {
    name: "Goldwin",
    styleTags: ["機能美", "ミニマル", "テック", "アウトドア"],
    genreCandidates: ["アウトドア", "ゴープコア", "テックウェア"],
    cultureCandidates: ["登山家/アウトドア"],
    itemStrengths: ["シェルジャケット", "ダウン", "機能パンツ"],
    materialSignals: ["ナイロン", "フリース", "化繊光沢"],
    colorSignals: ["オールブラック", "低彩度", "ニュートラル"],
    silhouetteSignals: ["Iライン", "ワイド", "オーバーサイズ"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "high",
    searchKeywords: ["Goldwin", "ゴールドウィン", "Goldwin jacket", "テックウェア"],
  },
  {
    name: "The North Face",
    styleTags: ["アウトドア定番", "機能的", "ストリート転用", "ロゴ"],
    genreCandidates: ["アウトドア", "ゴープコア", "アーバンアウトドア"],
    cultureCandidates: ["登山家/アウトドア"],
    itemStrengths: ["ヌプシダウン", "マウンテンパーカー", "フリース"],
    materialSignals: ["ナイロン", "フリース", "化繊光沢"],
    colorSignals: ["オールブラック", "アースカラー", "差し色アクセント", "ニュートラル"],
    silhouetteSignals: ["オーバーサイズ", "ボックス", "レイヤード"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["The North Face", "ザノースフェイス", "ノースフェイス", "ヌプシ"],
  },
  {
    name: "Arc'teryx",
    styleTags: ["高機能", "テック", "ミニマル", "都市アウトドア"],
    genreCandidates: ["ゴープコア", "アウトドア", "テックウェア"],
    cultureCandidates: ["登山家/アウトドア"],
    itemStrengths: ["ハードシェル", "ウィンドシェル", "バックパック"],
    materialSignals: ["ナイロン", "化繊光沢", "フリース"],
    colorSignals: ["オールブラック", "低彩度", "ニュートラル"],
    silhouetteSignals: ["Iライン", "レイヤード"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "high",
    searchKeywords: ["Arc'teryx", "アークテリクス", "Arcteryx jacket", "ゴープコア"],
  },
  {
    name: "Salomon",
    styleTags: ["トレイルシューズ", "ゴープコア", "テック", "機能"],
    genreCandidates: ["ゴープコア", "アウトドア", "アーバンアウトドア"],
    cultureCandidates: ["登山家/アウトドア"],
    itemStrengths: ["トレイルスニーカー", "シューズ"],
    materialSignals: ["ナイロン", "メッシュ", "化繊光沢"],
    colorSignals: ["オールブラック", "低彩度", "差し色アクセント", "ニュートラル"],
    silhouetteSignals: [],
    eraSignals: ["2010s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["Salomon", "サロモン", "Salomon XT-6", "トレイルスニーカー"],
  },
  {
    name: "DIESEL",
    styleTags: ["Y2Kデニム", "ロゴ", "光沢", "タイト"],
    genreCandidates: ["Y2K/McBling", "Y2K/00sストリート", "ストリート"],
    cultureCandidates: ["クラブ/レイヴ/テクノ"],
    itemStrengths: ["デニム", "ロゴT", "アウター"],
    materialSignals: ["デニム", "レザー", "化繊光沢"],
    colorSignals: ["ビビッド", "差し色アクセント", "ダークトーン"],
    silhouetteSignals: ["タイト", "ジャストサイズ", "ワイド"],
    eraSignals: ["2000s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["DIESEL", "ディーゼル", "Diesel denim", "Y2K デニム"],
  },
  {
    name: "HYSTERIC GLAMOUR",
    styleTags: ["ロックY2K", "グラフィック", "挑発的", "ガーリーロック"],
    genreCandidates: ["Y2K/McBling", "ロック", "ストリート"],
    cultureCandidates: ["東京/原宿", "パンク/ロック"],
    itemStrengths: ["グラフィックT", "デニム", "レザー"],
    materialSignals: ["デニム", "レザー", "コットン"],
    colorSignals: ["ビビッド", "差し色アクセント", "モノトーン", "ダークトーン"],
    silhouetteSignals: ["タイト", "ジャストサイズ", "上短め下太め"],
    eraSignals: ["1990s", "2000s"],
    priceTier: "mid",
    searchKeywords: ["HYSTERIC GLAMOUR", "ヒステリックグラマー", "ヒステリック", "ロックT"],
  },
  {
    name: "X-girl",
    styleTags: ["ガーリーストリート", "Y2K", "ロゴ", "スケート"],
    genreCandidates: ["Y2K/McBling", "Y2K/00sストリート", "ストリート"],
    cultureCandidates: ["東京/原宿", "スケーター"],
    itemStrengths: ["ロゴT", "ミニスカート", "スウェット"],
    materialSignals: ["コットン", "ナイロン", "デニム"],
    colorSignals: ["ビビッド", "差し色アクセント", "パステル", "モノトーン"],
    silhouetteSignals: ["上短め下太め", "タイト", "ワイド"],
    eraSignals: ["2000s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["X-girl", "エックスガール", "X-girl tee", "Y2K ストリート"],
  },
  {
    name: "Ed Hardy",
    styleTags: ["McBling", "タトゥーグラフィック", "派手", "セレブY2K"],
    genreCandidates: ["Y2K/McBling", "ストリート"],
    cultureCandidates: ["LA", "クラブ/レイヴ/テクノ"],
    itemStrengths: ["タトゥーグラフィックT", "トラッカーキャップ", "デニム"],
    materialSignals: ["コットン", "デニム", "化繊光沢"],
    colorSignals: ["ビビッド", "差し色アクセント", "ダークトーン"],
    silhouetteSignals: ["タイト", "ジャストサイズ", "上短め下太め"],
    eraSignals: ["2000s"],
    priceTier: "mid",
    searchKeywords: ["Ed Hardy", "エドハーディー", "Ed Hardy tee", "McBling"],
  },
  {
    name: "Von Dutch",
    styleTags: ["McBling", "トラッカーキャップ", "セレブY2K", "派手"],
    genreCandidates: ["Y2K/McBling", "ストリート"],
    cultureCandidates: ["LA", "クラブ/レイヴ/テクノ"],
    itemStrengths: ["トラッカーキャップ", "グラフィックT", "デニム"],
    materialSignals: ["コットン", "デニム", "メッシュ"],
    colorSignals: ["ビビッド", "差し色アクセント", "モノトーン"],
    silhouetteSignals: ["タイト", "ジャストサイズ"],
    eraSignals: ["2000s"],
    priceTier: "low",
    searchKeywords: ["Von Dutch", "ヴォンダッチ", "Von Dutch cap", "McBling"],
  },
  {
    name: "REFLEM",
    styleTags: ["地雷系", "病みかわ", "黒×パステル", "ダークガーリー"],
    genreCandidates: ["地雷系", "サブカル/病みかわ"],
    cultureCandidates: ["東京/原宿", "ヴィジュアル系/エモ"],
    itemStrengths: ["ミニスカート", "パーカー", "カットソー"],
    materialSignals: ["コットン", "化繊光沢", "メッシュ"],
    colorSignals: ["オールブラック", "ダークトーン", "パステル", "差し色アクセント"],
    silhouetteSignals: ["上短め下太め", "Aライン", "タイト"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "low",
    searchKeywords: ["REFLEM", "レフレム", "地雷系", "病みかわ"],
  },
  {
    name: "TRAVAS TOKYO",
    styleTags: ["原宿サブカル", "病みかわ", "キャラグラフィック", "ストリート"],
    genreCandidates: ["サブカル/病みかわ", "地雷系", "ストリート"],
    cultureCandidates: ["東京/原宿"],
    itemStrengths: ["パーカー", "ビッグT", "カットソー"],
    materialSignals: ["コットン", "化繊光沢", "メッシュ"],
    colorSignals: ["オールブラック", "モノトーン", "パステル", "差し色アクセント"],
    silhouetteSignals: ["オーバーサイズ", "ボックス", "タイト"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "low",
    searchKeywords: ["TRAVAS TOKYO", "トラヴァストーキョー", "病みかわ", "原宿系"],
  },
  {
    name: "Amilige",
    styleTags: ["量産型", "病みかわ", "黒甘", "ガーリー"],
    genreCandidates: ["サブカル/病みかわ", "地雷系"],
    cultureCandidates: ["東京/原宿", "J-POPアイドル"],
    itemStrengths: ["ワンピース", "スカート", "ブラウス"],
    materialSignals: ["サテン/シルク", "コットン", "化繊光沢"],
    colorSignals: ["オールブラック", "パステル", "ベージュ系", "差し色アクセント"],
    silhouetteSignals: ["Aライン", "上短め下太め", "タイト"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "low",
    searchKeywords: ["Amilige", "アミリージュ", "量産型", "病みかわ"],
  },
  {
    name: "Ank Rouge",
    styleTags: ["量産型", "甘めガーリー", "淡色", "フリル"],
    genreCandidates: ["量産型", "フェミニン/ガーリー"],
    cultureCandidates: ["東京/原宿", "J-POPアイドル"],
    itemStrengths: ["ワンピース", "スカート", "ブラウス"],
    materialSignals: ["サテン/シルク", "コットン", "化繊光沢"],
    colorSignals: ["パステル", "ベージュ系", "差し色アクセント"],
    silhouetteSignals: ["Aライン", "上短め下太め", "タイト"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "low",
    searchKeywords: ["Ank Rouge", "アンクルージュ", "量産型", "ガーリー"],
  },
  {
    name: "ROJITA",
    styleTags: ["量産型", "きれいめガーリー", "淡色", "リボン"],
    genreCandidates: ["量産型", "フェミニン/ガーリー"],
    cultureCandidates: ["東京/原宿", "J-POPアイドル"],
    itemStrengths: ["ワンピース", "スカート", "ブラウス"],
    materialSignals: ["サテン/シルク", "コットン", "化繊光沢"],
    colorSignals: ["パステル", "ベージュ系", "オールブラック", "差し色アクセント"],
    silhouetteSignals: ["Aライン", "上短め下太め", "タイト"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "low",
    searchKeywords: ["ROJITA", "ロジータ", "量産型", "ガーリー"],
  },
  {
    name: "A Bathing Ape",
    styleTags: ["裏原", "カモ", "ロゴ", "ストリート"],
    genreCandidates: ["裏原系", "90sストリート", "ストリート"],
    cultureCandidates: ["東京/原宿", "ヒップホップ", "スケーター"],
    itemStrengths: ["シャークパーカー", "グラフィックT", "カモアイテム"],
    materialSignals: ["コットン", "ナイロン", "デニム"],
    colorSignals: ["差し色アクセント", "モノトーン", "ビビッド", "オールブラック"],
    silhouetteSignals: ["オーバーサイズ", "ボックス", "ワイド"],
    eraSignals: ["1990s", "2000s"],
    priceTier: "mid",
    searchKeywords: ["A Bathing Ape", "BAPE", "ベイプ", "裏原"],
  },
  {
    name: "NEIGHBORHOOD",
    styleTags: ["裏原", "ミリタリー", "バイカー", "硬派"],
    genreCandidates: ["裏原系", "ミリタリー", "ストリート"],
    cultureCandidates: ["東京/原宿", "パンク/ロック", "バイカー"],
    itemStrengths: ["ミリタリージャケット", "デニム", "グラフィックT"],
    materialSignals: ["コットン", "デニム", "レザー"],
    colorSignals: ["オールブラック", "モノトーン", "アースカラー", "ダークトーン"],
    silhouetteSignals: ["ワイド", "ボックス", "Iライン"],
    eraSignals: ["2000s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["NEIGHBORHOOD", "ネイバーフッド", "裏原", "ミリタリー"],
  },
  {
    name: "WTAPS",
    styleTags: ["裏原", "ミリタリー・ワーク", "機能", "渋い"],
    genreCandidates: ["裏原系", "ミリタリー", "ストリート"],
    cultureCandidates: ["東京/原宿", "パンク/ロック"],
    itemStrengths: ["ミリタリーシャツ", "カーゴ", "アウター"],
    materialSignals: ["コットン", "ナイロン", "デニム"],
    colorSignals: ["オールブラック", "アースカラー", "モノトーン", "ダークトーン"],
    silhouetteSignals: ["ワイド", "オーバーサイズ", "ボックス"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["WTAPS", "ダブルタップス", "裏原", "ミリタリー"],
  },
  {
    name: "HUMAN MADE",
    styleTags: ["裏原", "アメカジ", "レトログラフィック", "ロゴ"],
    genreCandidates: ["裏原系", "アメカジ", "ストリート"],
    cultureCandidates: ["東京/原宿", "ヒップホップ"],
    itemStrengths: ["グラフィックT", "スウェット", "ヴァーシティジャケット"],
    materialSignals: ["コットン", "デニム", "ナイロン"],
    colorSignals: ["差し色アクセント", "モノトーン", "アースカラー"],
    silhouetteSignals: ["ボックス", "オーバーサイズ", "ジャストサイズ"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["HUMAN MADE", "ヒューマンメイド", "裏原", "アメカジ"],
  },
  {
    name: "Cav Empt",
    styleTags: ["ディストピア", "テックストリート", "グラフィック", "サイバー"],
    genreCandidates: ["テックストリート", "ストリート", "サイバーパンク/近未来"],
    cultureCandidates: ["東京/原宿", "クラブ/レイヴ/テクノ", "アーティスト/クリエイター"],
    itemStrengths: ["グラフィックパーカー", "ナイロンアウター", "ビッグT"],
    materialSignals: ["コットン", "ナイロン", "化繊光沢"],
    colorSignals: ["モノトーン", "オールブラック", "差し色アクセント", "ダークトーン"],
    silhouetteSignals: ["オーバーサイズ", "ボックス", "ワイド"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["Cav Empt", "C.E.", "シーイー", "テックストリート"],
  },
  {
    name: "ACRONYM",
    styleTags: ["テックウェア", "黒", "機能ギミック", "都市"],
    genreCandidates: ["テックウェア", "テックストリート", "サイバーパンク/近未来"],
    cultureCandidates: ["ベルリン", "アーティスト/クリエイター"],
    itemStrengths: ["テックシェル", "カーゴ", "ジャケット"],
    materialSignals: ["ナイロン", "化繊光沢", "フリース"],
    colorSignals: ["オールブラック", "ダークトーン", "モノトーン", "低彩度"],
    silhouetteSignals: ["Iライン", "レイヤード", "オーバーサイズ"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "high",
    searchKeywords: ["ACRONYM", "アクロニウム", "テックウェア", "テックストリート"],
  },
  {
    name: "Stone Island",
    styleTags: ["テック素材", "バッジ", "スポーツストリート", "染色"],
    genreCandidates: ["スポーツストリート", "テックストリート", "ストリート"],
    cultureCandidates: [],
    itemStrengths: ["ガーメントダイジャケット", "ニット", "カーゴ"],
    materialSignals: ["ナイロン", "化繊光沢", "コットン", "フリース"],
    colorSignals: ["オールブラック", "アースカラー", "差し色アクセント", "ニュートラル"],
    silhouetteSignals: ["オーバーサイズ", "ボックス", "Iライン"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "high",
    searchKeywords: ["Stone Island", "ストーンアイランド", "テックストリート", "スポーツストリート"],
  },
  {
    name: "C.P. Company",
    styleTags: ["テック素材", "ゴーグル", "スポーツストリート", "ユーティリティ"],
    genreCandidates: ["スポーツストリート", "テックストリート", "ストリート"],
    cultureCandidates: [],
    itemStrengths: ["ゴーグルジャケット", "オーバーシャツ", "カーゴ"],
    materialSignals: ["ナイロン", "化繊光沢", "コットン"],
    colorSignals: ["オールブラック", "アースカラー", "ニュートラル", "差し色アクセント"],
    silhouetteSignals: ["オーバーサイズ", "ボックス", "Iライン"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "high",
    searchKeywords: ["C.P. Company", "シーピーカンパニー", "テックストリート", "スポーツストリート"],
  },
  {
    name: "11 by Boris Bidjan Saberi",
    styleTags: ["黒テック", "ダーク", "レザー", "アヴァンギャルド"],
    genreCandidates: ["テックウェア", "ダーク/ブラックモード", "テックストリート"],
    cultureCandidates: ["ベルリン", "アーティスト/クリエイター"],
    itemStrengths: ["テックジャケット", "レザー", "カーゴ"],
    materialSignals: ["レザー", "ナイロン", "化繊光沢"],
    colorSignals: ["オールブラック", "ダークトーン", "モノトーン"],
    silhouetteSignals: ["レイヤード", "Iライン", "ドレープ"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "high",
    searchKeywords: ["11 by Boris Bidjan Saberi", "ボリスビジャンサベリ", "テックウェア", "黒"],
  },
  {
    name: "Nike ACG",
    styleTags: ["アウトドア", "機能", "ゴープコア", "ナイキ"],
    genreCandidates: ["アウトドア", "アーバンアウトドア", "ゴープコア"],
    cultureCandidates: ["登山家/アウトドア", "スケーター"],
    itemStrengths: ["シェル", "カーゴ", "トレイルスニーカー"],
    materialSignals: ["ナイロン", "フリース", "化繊光沢", "メッシュ"],
    colorSignals: ["オールブラック", "アースカラー", "差し色アクセント", "低彩度"],
    silhouetteSignals: ["オーバーサイズ", "レイヤード", "ボックス"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["Nike ACG", "ナイキACG", "ACG", "ゴープコア"],
  },
  {
    name: "Levi's",
    styleTags: ["アメカジ", "デニム定番", "古着", "ヘリテージ"],
    genreCandidates: ["アメカジ", "アメリカ古着", "デニムスタイル"],
    cultureCandidates: ["古着屋店員"],
    itemStrengths: ["デニム", "トラッカージャケット", "Tシャツ"],
    materialSignals: ["デニム", "コットン"],
    colorSignals: ["ネイビー基調", "アースカラー", "ニュートラル"],
    silhouetteSignals: ["ジャストサイズ", "ワイド", "ボックス"],
    eraSignals: ["1950s", "1970s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["Levi's", "リーバイス", "501", "デニム"],
  },
  {
    name: "Lee",
    styleTags: ["アメカジ", "ワークデニム", "古着", "ヘリテージ"],
    genreCandidates: ["アメカジ", "ワークスタイル", "アメリカ古着"],
    cultureCandidates: ["古着屋店員"],
    itemStrengths: ["デニム", "オーバーオール", "カバーオール"],
    materialSignals: ["デニム", "コットン"],
    colorSignals: ["ネイビー基調", "アースカラー", "ニュートラル"],
    silhouetteSignals: ["ジャストサイズ", "ワイド", "ボックス"],
    eraSignals: ["1950s", "1970s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["Lee", "リー", "デニム", "ワーク"],
  },
  {
    name: "Carhartt WIP",
    styleTags: ["ワーク", "ストリート転用", "ダック生地", "ロゴ"],
    genreCandidates: ["ワークスタイル", "ストリート", "アメカジ"],
    cultureCandidates: ["スケーター", "古着屋店員"],
    itemStrengths: ["ダックジャケット", "カーゴ", "Tシャツ"],
    materialSignals: ["コットン", "デニム"],
    colorSignals: ["アースカラー", "ネイビー基調", "ダークトーン", "ニュートラル"],
    silhouetteSignals: ["ワイド", "オーバーサイズ", "ボックス"],
    eraSignals: ["1990s", "2010s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["Carhartt WIP", "カーハート", "ワーク", "ストリート"],
  },
  {
    name: "Champion",
    styleTags: ["アメカジ", "スウェット定番", "カレッジ", "ロゴ"],
    genreCandidates: ["アメカジ", "スポーツストリート", "アメリカ古着"],
    cultureCandidates: ["古着屋店員", "スケーター"],
    itemStrengths: ["リバースウィーブスウェット", "パーカー", "Tシャツ"],
    materialSignals: ["コットン", "起毛"],
    colorSignals: ["ニュートラル", "ネイビー基調", "アースカラー", "差し色アクセント"],
    silhouetteSignals: ["オーバーサイズ", "ボックス", "ジャストサイズ"],
    eraSignals: ["1990s", "2000s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["Champion", "チャンピオン", "リバースウィーブ", "スウェット"],
  },
  {
    name: "Red Wing",
    styleTags: ["ワークブーツ", "レザー", "ヘリテージ", "堅牢"],
    genreCandidates: ["アメカジ", "ワークスタイル", "アメリカ古着"],
    cultureCandidates: ["古着屋店員", "バイカー"],
    itemStrengths: ["ワークブーツ", "レザーブーツ"],
    materialSignals: ["レザー", "スエード"],
    colorSignals: ["アースカラー", "ダークトーン", "ニュートラル"],
    silhouetteSignals: [],
    eraSignals: ["1950s", "1970s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["Red Wing", "レッドウィング", "ワークブーツ", "アイリッシュセッター"],
  },
  {
    name: "SNIDEL",
    styleTags: ["きれいめフェミニン", "トレンド", "甘め", "ツイード"],
    genreCandidates: ["フェミニン/ガーリー", "ロマンティック"],
    cultureCandidates: ["モデル私服(オフデューティ)", "カフェ店員/バリスタ"],
    itemStrengths: ["ワンピース", "スカート", "ニット"],
    materialSignals: ["ニット", "サテン/シルク", "ツイード"],
    colorSignals: ["ベージュ系", "パステル", "ニュートラル"],
    silhouetteSignals: ["Aライン", "タイト", "上短め下太め"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["SNIDEL", "スナイデル", "フェミニン", "ワンピース"],
  },
  {
    name: "Her lip to",
    styleTags: ["大人フェミニン", "ロマンティック", "上品", "トレンド"],
    genreCandidates: ["フェミニン/ガーリー", "ロマンティック"],
    cultureCandidates: ["モデル私服(オフデューティ)"],
    itemStrengths: ["ワンピース", "ブラウス", "スカート"],
    materialSignals: ["サテン/シルク", "ニット", "コットン"],
    colorSignals: ["ベージュ系", "ニュートラル", "パステル"],
    silhouetteSignals: ["Aライン", "タイト", "Iライン"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["Her lip to", "ハーリップトゥ", "フェミニン", "ワンピース"],
  },
  {
    name: "épine",
    styleTags: ["甘めガーリー", "リボン", "コケット", "淡色"],
    genreCandidates: ["フェミニン/ガーリー", "ロマンティック", "コケット"],
    cultureCandidates: ["モデル私服(オフデューティ)"],
    itemStrengths: ["ワンピース", "リボン小物", "ブラウス"],
    materialSignals: ["サテン/シルク", "コットン", "ニット"],
    colorSignals: ["パステル", "ベージュ系", "ニュートラル"],
    silhouetteSignals: ["Aライン", "タイト", "上短め下太め"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "low",
    searchKeywords: ["épine", "エピヌ", "ガーリー", "リボン"],
  },
  {
    name: "Mardi Mercredi",
    styleTags: ["韓国ガーリー", "フラワー刺繍", "淡色", "きれいめ甘め"],
    genreCandidates: ["フレンチ/韓国ガーリー", "フェミニン/ガーリー", "ロマンティック"],
    cultureCandidates: ["モデル私服(オフデューティ)"],
    itemStrengths: ["ニットカーディガン", "ワンピース", "ブラウス"],
    materialSignals: ["ニット", "コットン", "サテン/シルク"],
    colorSignals: ["ベージュ系", "パステル", "ニュートラル"],
    silhouetteSignals: ["Aライン", "タイト", "ジャストサイズ"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "low",
    searchKeywords: ["Mardi Mercredi", "マルディメクルディ", "韓国ガーリー", "フラワー"],
  },
  {
    name: "NICE CLAUP",
    styleTags: ["カジュアルフェミニン", "甘め", "淡色", "きれいめ"],
    genreCandidates: ["フェミニン/ガーリー", "ロマンティック"],
    cultureCandidates: ["モデル私服(オフデューティ)"],
    itemStrengths: ["ワンピース", "ブラウス", "スカート"],
    materialSignals: ["コットン", "ニット", "サテン/シルク"],
    colorSignals: ["ベージュ系", "パステル", "ニュートラル"],
    silhouetteSignals: ["Aライン", "タイト", "上短め下太め"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "low",
    searchKeywords: ["NICE CLAUP", "ナイスクラップ", "フェミニン", "ガーリー"],
  },
  {
    name: "Alice and the Pirates",
    styleTags: ["ゴシックロリータ", "クラシカル", "黒レース", "耽美"],
    genreCandidates: ["ゴシックロリータ", "ゴシック/ゴス", "ロリータ"],
    cultureCandidates: ["東京/原宿", "ヴィジュアル系/エモ"],
    itemStrengths: ["ワンピース", "ブラウス", "ジャケット"],
    materialSignals: ["サテン/シルク", "コットン", "レザー"],
    colorSignals: ["オールブラック", "ダークトーン", "差し色アクセント"],
    silhouetteSignals: ["Aライン", "レイヤード", "タイト"],
    eraSignals: ["2000s", "2010s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["Alice and the Pirates", "アリスアンドザパイレーツ", "ゴシックロリータ", "ゴス"],
  },
  {
    name: "h.NAOTO",
    styleTags: ["V系", "ゴス", "アシンメトリー", "黒"],
    genreCandidates: ["ヴィジュアル系", "ゴシック/ゴス", "ゴシックロリータ"],
    cultureCandidates: ["東京/原宿", "ヴィジュアル系/エモ"],
    itemStrengths: ["アシンメトリーカットソー", "スカート", "ジャケット"],
    materialSignals: ["コットン", "レザー", "サテン/シルク"],
    colorSignals: ["オールブラック", "ダークトーン", "差し色アクセント"],
    silhouetteSignals: ["レイヤード", "タイト", "Aライン"],
    eraSignals: ["2000s", "2010s"],
    priceTier: "mid",
    searchKeywords: ["h.NAOTO", "エイチナオト", "ヴィジュアル系", "ゴス"],
  },
  {
    name: "Moi-même-Moitié",
    styleTags: ["エレガントゴシックロリータ", "クラシカル", "黒紺", "耽美"],
    genreCandidates: ["ゴシックロリータ", "ゴシック/ゴス", "ロリータ"],
    cultureCandidates: ["東京/原宿", "ヴィジュアル系/エモ"],
    itemStrengths: ["ワンピース", "ジャンパースカート", "ブラウス"],
    materialSignals: ["サテン/シルク", "ウール", "コットン"],
    colorSignals: ["オールブラック", "ダークトーン", "ネイビー基調"],
    silhouetteSignals: ["Aライン", "レイヤード", "タイト"],
    eraSignals: ["2000s", "2010s"],
    priceTier: "high",
    searchKeywords: ["Moi-même-Moitié", "モワメームモワティエ", "ゴシックロリータ", "ゴス"],
  },
  {
    name: "Vivienne Westwood",
    styleTags: ["英国パンク", "ヴィヴィアン", "タータン", "オーブ"],
    genreCandidates: ["パンク", "ゴシック/ゴス", "モード"],
    cultureCandidates: ["ロンドン", "パンク/ロック"],
    itemStrengths: ["コルセット", "タータンアイテム", "ジュエリー"],
    materialSignals: ["ウール", "サテン/シルク", "レザー"],
    colorSignals: ["ダークトーン", "オールブラック", "差し色アクセント"],
    silhouetteSignals: ["タイト", "ドレープ", "Aライン"],
    eraSignals: ["1980s", "1990s", "2020s"],
    priceTier: "high",
    searchKeywords: ["Vivienne Westwood", "ヴィヴィアンウエストウッド", "パンク", "オーブ"],
  },
  {
    name: "ANN DEMEULEMEESTER",
    styleTags: ["ダークモード", "詩的な黒", "ドレープ", "アンドロジナス"],
    genreCandidates: ["ダーク/ブラックモード", "モード", "アヴァンギャルド/脱構築"],
    cultureCandidates: ["アーティスト/クリエイター", "パリ"],
    itemStrengths: ["レザージャケット", "ロングシャツ", "ドレープトップス"],
    materialSignals: ["レザー", "ウール", "コットン"],
    colorSignals: ["オールブラック", "ダークトーン", "モノトーン"],
    silhouetteSignals: ["ドレープ", "レイヤード", "Iライン"],
    eraSignals: ["1990s", "2000s", "2010s"],
    priceTier: "luxury",
    searchKeywords: ["ANN DEMEULEMEESTER", "アンドゥムルメステール", "ダークモード", "黒"],
  },
  {
    name: "Ralph Lauren",
    styleTags: ["アイビー", "プレッピー", "上品トラッド", "ポロ"],
    genreCandidates: ["アイビー/トラッド", "プレッピー", "オールドマネー"],
    cultureCandidates: ["学園/カレッジ映画", "編集者/スタイリスト"],
    itemStrengths: ["ポロシャツ", "オックスフォードシャツ", "ブレザー"],
    materialSignals: ["コットン", "ウール", "ニット"],
    colorSignals: ["ネイビー基調", "ベージュ系", "ニュートラル"],
    silhouetteSignals: ["ジャストサイズ", "Iライン", "ボックス"],
    eraSignals: ["1980s", "1990s", "2020s"],
    priceTier: "high",
    searchKeywords: ["Ralph Lauren", "ラルフローレン", "ポロ", "アイビー"],
  },
  {
    name: "Brooks Brothers",
    styleTags: ["正統アイビー", "トラッド", "ボタンダウン", "クラシック"],
    genreCandidates: ["アイビー/トラッド", "クラシック/ドレス", "プレッピー"],
    cultureCandidates: ["学園/カレッジ映画", "編集者/スタイリスト"],
    itemStrengths: ["ボタンダウンシャツ", "ブレザー", "スーツ"],
    materialSignals: ["コットン", "ウール", "ツイード"],
    colorSignals: ["ネイビー基調", "ベージュ系", "ニュートラル"],
    silhouetteSignals: ["ジャストサイズ", "Iライン", "ボックス"],
    eraSignals: ["1950s", "1960s", "2020s"],
    priceTier: "high",
    searchKeywords: ["Brooks Brothers", "ブルックスブラザーズ", "アイビー", "ボタンダウン"],
  },
  {
    name: "J.PRESS",
    styleTags: ["正統アイビー", "カレッジ", "トラッド", "ツイード"],
    genreCandidates: ["アイビー/トラッド", "プレッピー", "クラシック/ドレス"],
    cultureCandidates: ["学園/カレッジ映画", "編集者/スタイリスト"],
    itemStrengths: ["ブレザー", "チノ", "ニットベスト"],
    materialSignals: ["ウール", "コットン", "ツイード"],
    colorSignals: ["ネイビー基調", "ベージュ系", "ニュートラル"],
    silhouetteSignals: ["ジャストサイズ", "Iライン", "ボックス"],
    eraSignals: ["1960s", "1980s", "2020s"],
    priceTier: "high",
    searchKeywords: ["J.PRESS", "ジェイプレス", "アイビー", "トラッド"],
  },
  {
    name: "Lacoste",
    styleTags: ["プレッピー", "ポロ", "カレッジ", "スポーティ"],
    genreCandidates: ["プレッピー", "アイビー/トラッド", "スポーティ/アスレジャー"],
    cultureCandidates: ["学園/カレッジ映画", "編集者/スタイリスト"],
    itemStrengths: ["ポロシャツ", "ニット", "トラックジャケット"],
    materialSignals: ["コットン", "ニット"],
    colorSignals: ["ネイビー基調", "差し色アクセント", "ニュートラル", "ベージュ系"],
    silhouetteSignals: ["ジャストサイズ", "ボックス", "Iライン"],
    eraSignals: ["1980s", "1990s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["Lacoste", "ラコステ", "ポロ", "プレッピー"],
  },
  {
    name: "Barbour",
    styleTags: ["英国クラシック", "ワックスドコットン", "カントリー", "アウター"],
    genreCandidates: ["クラシック/ドレス", "アイビー/トラッド", "アウトドア"],
    cultureCandidates: ["ロンドン", "登山家/アウトドア"],
    itemStrengths: ["ワックスドジャケット", "キルティングジャケット", "ジレ"],
    materialSignals: ["コットン", "ウール", "コーデュロイ"],
    colorSignals: ["アースカラー", "ネイビー基調", "ダークトーン", "ニュートラル"],
    silhouetteSignals: ["Iライン", "ジャストサイズ", "ボックス"],
    eraSignals: ["1980s", "1990s", "2020s"],
    priceTier: "high",
    searchKeywords: ["Barbour", "バブアー", "英国", "ワックスドジャケット"],
  },
  {
    name: "EGOIST",
    styleTags: ["黒ギャル", "タイト", "Y2K", "色気"],
    genreCandidates: ["ギャル", "Y2K/McBling", "フェミニン/ガーリー"],
    cultureCandidates: ["東京/原宿", "クラブ/レイヴ/テクノ"],
    itemStrengths: ["タイトワンピース", "カットソー", "スカート"],
    materialSignals: ["化繊光沢", "レザー", "コットン"],
    colorSignals: ["オールブラック", "ダークトーン", "差し色アクセント"],
    silhouetteSignals: ["タイト", "ジャストサイズ", "上短め下太め"],
    eraSignals: ["2000s", "2010s"],
    priceTier: "mid",
    searchKeywords: ["EGOIST", "エゴイスト", "ギャル", "Y2K"],
  },
  {
    name: "SLY",
    styleTags: ["クールギャル", "黒", "モードギャル", "タイト"],
    genreCandidates: ["ギャル", "Y2K/00sストリート", "モード"],
    cultureCandidates: ["東京/原宿", "モデル私服(オフデューティ)"],
    itemStrengths: ["デニム", "レザージャケット", "ワンピース"],
    materialSignals: ["デニム", "レザー", "化繊光沢"],
    colorSignals: ["オールブラック", "ダークトーン", "モノトーン"],
    silhouetteSignals: ["タイト", "Iライン", "上短め下太め"],
    eraSignals: ["2000s", "2010s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["SLY", "スライ", "ギャル", "デニム"],
  },
  {
    name: "moussy",
    styleTags: ["デニムギャル", "Y2K", "ヴィンテージ加工", "タイト"],
    genreCandidates: ["ギャル", "Y2K/00sストリート", "アメカジ"],
    cultureCandidates: ["東京/原宿", "モデル私服(オフデューティ)"],
    itemStrengths: ["デニム", "カットソー", "アウター"],
    materialSignals: ["デニム", "化繊光沢", "コットン"],
    colorSignals: ["オールブラック", "ダークトーン", "ニュートラル"],
    silhouetteSignals: ["タイト", "ワイド", "ジャストサイズ"],
    eraSignals: ["2000s", "2010s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["moussy", "マウジー", "ギャル", "デニム"],
  },
  {
    name: "EMODA",
    styleTags: ["モードギャル", "黒", "クール", "タイト"],
    genreCandidates: ["ギャル", "モード", "Y2K/00sストリート"],
    cultureCandidates: ["東京/原宿", "モデル私服(オフデューティ)"],
    itemStrengths: ["タイトワンピース", "パンツ", "アウター"],
    materialSignals: ["化繊光沢", "レザー", "デニム"],
    colorSignals: ["オールブラック", "モノトーン", "ダークトーン"],
    silhouetteSignals: ["タイト", "Iライン", "上短め下太め"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["EMODA", "エモダ", "ギャル", "モード"],
  },
  {
    name: "GYDA",
    styleTags: ["スポーティギャル", "Y2K", "タイト", "ヘルシー"],
    genreCandidates: ["ギャル", "Y2K/McBling", "スポーティ/アスレジャー"],
    cultureCandidates: ["東京/原宿", "モデル私服(オフデューティ)"],
    itemStrengths: ["クロップドトップ", "レギンス", "パーカー"],
    materialSignals: ["化繊光沢", "コットン", "デニム"],
    colorSignals: ["オールブラック", "ダークトーン", "差し色アクセント"],
    silhouetteSignals: ["タイト", "上短め下太め", "ジャストサイズ"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["GYDA", "ジェイダ", "ギャル", "Y2K"],
  },
  {
    name: "Margaret Howell",
    styleTags: ["英国クラシック", "上質ベーシック", "知的", "ナチュラル"],
    genreCandidates: ["クラシック/ドレス", "アイビー/トラッド", "ミニマル"],
    cultureCandidates: ["ロンドン", "書店員/文化系"],
    itemStrengths: ["シャツ", "ニット", "テーラードジャケット"],
    materialSignals: ["ウール", "コットン", "ニット"],
    colorSignals: ["ニュートラル", "アースカラー", "ネイビー基調", "低彩度"],
    silhouetteSignals: ["Iライン", "ジャストサイズ", "ボックス"],
    eraSignals: ["1990s", "2010s", "2020s"],
    priceTier: "high",
    searchKeywords: ["Margaret Howell", "マーガレットハウエル", "英国", "クラシック"],
  },
  {
    name: "MHL.",
    styleTags: ["英国ワーク", "ミリタリー", "無骨ベーシック", "実用"],
    genreCandidates: ["ワークスタイル", "ミリタリー", "クラシック/ドレス"],
    cultureCandidates: ["ロンドン", "書店員/文化系"],
    itemStrengths: ["ワークジャケット", "ファティーグパンツ", "ボーダーカットソー"],
    materialSignals: ["コットン", "ウール", "コーデュロイ"],
    colorSignals: ["アースカラー", "ニュートラル", "ネイビー基調", "低彩度"],
    silhouetteSignals: ["ボックス", "ワイド", "Iライン"],
    eraSignals: ["1990s", "2010s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["MHL.", "エムエイチエル", "ワーク", "ミリタリー"],
  },
  {
    name: "A.P.C.",
    styleTags: ["フレンチミニマル", "上質デニム", "シンプル", "きれいめ"],
    genreCandidates: ["フレンチシック/パリジャン", "ミニマル", "クラシック/ドレス", "デニムスタイル"],
    cultureCandidates: ["パリ", "編集者/スタイリスト"],
    itemStrengths: ["ローデニム", "シャツ", "レザーバッグ"],
    materialSignals: ["デニム", "コットン", "ウール", "レザー"],
    colorSignals: ["ネイビー基調", "ニュートラル", "低彩度", "オールブラック"],
    silhouetteSignals: ["Iライン", "ジャストサイズ", "ボックス"],
    eraSignals: ["1990s", "2010s", "2020s"],
    priceTier: "high",
    searchKeywords: ["A.P.C.", "アーペーセー", "フレンチ", "デニム"],
  },
  {
    name: "COS",
    styleTags: ["モダンミニマル", "建築的", "クリーン", "ニュートラル"],
    genreCandidates: ["ミニマル", "ミニマルモード", "クラシック/ドレス"],
    cultureCandidates: ["北欧コペンハーゲン", "編集者/スタイリスト"],
    itemStrengths: ["ニット", "シャツ", "コート"],
    materialSignals: ["ウール", "コットン", "ニット"],
    colorSignals: ["ニュートラル", "低彩度", "オールブラック", "ベージュ系"],
    silhouetteSignals: ["Iライン", "ワイド", "ボックス"],
    eraSignals: ["2010s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["COS", "コス", "ミニマル", "モダン"],
  },
  {
    name: "Dr. Martens",
    styleTags: ["英国ブーツ", "パンク", "ダークアカデミア", "レザー"],
    genreCandidates: ["パンク", "ダークアカデミア", "ロック"],
    cultureCandidates: ["ロンドン", "パンク/ロック"],
    itemStrengths: ["8ホールブーツ", "ローファー", "シューズ"],
    materialSignals: ["レザー", "スエード"],
    colorSignals: ["オールブラック", "ダークトーン", "差し色アクセント"],
    silhouetteSignals: [],
    eraSignals: ["1990s", "2010s", "2020s"],
    priceTier: "mid",
    searchKeywords: ["Dr. Martens", "ドクターマーチン", "ブーツ", "パンク"],
  },
];
