// Sprint 42: 世界観の8パターン定数
//
// アプリ側でこの定数とユーザー回答のタグ集計を突き合わせ、最もスコアの高い
// パターンを採用する。Claude APIにはこのパターン+回答を渡し、
// 文章フィールド（plainSummary / unconsciousTendency / idealSelf 等）の
// 個別生成のみを任せる。色・素材・形・ブランド・音楽映画香水・firstPieceは
// このファイルの値が結果に直接コピーされる。

import type { WorldviewPattern } from "@/types/index";

export const WORLDVIEW_PATTERNS: WorldviewPattern[] = [
  {
    id:   "quiet-observer",
    name: "静謐な観察者",
    coreTags: ["quiet", "minimal", "intellectual", "nostalgic"],
    psychologicalCore: "周囲を見ているが、自分が見られることは静かに望む。語らずに佇まいで伝える人。",
    clothingRole: "自分を整えて、必要以上に主張しない静けさをまとう",
    avoidImpressions: ["派手すぎ", "目立ちすぎ", "量産型"],
    idealSelf: "言葉を尽くさずとも、その場にいるだけで知性が伝わる人",
    colors: ["オフホワイト", "墨色", "グレージュ", "薄墨", "生成り"],
    materials: ["コットン", "リネン", "ウール", "上質な綿"],
    silhouettes: ["Iライン", "ストレート", "ゆるやかなドレープ", "ロング丈"],
    accessories: ["細い革ベルト", "シルバーの細い時計", "布のトート"],
    brands: ["COS", "Auralee", "Lemaire", "Comoli", "Margaret Howell", "Studio Nicholson"],
    music:    ["アンビエント", "坂本龍一系", "Nils Frahm"],
    films:    ["是枝裕和", "ジム・ジャームッシュ", "ヴィム・ヴェンダース"],
    fragrance:["ヒノキ", "墨", "白檀"],
    firstPiece: {
      name:        "白の細番手シャツ",
      why:         "色味を持たない一枚があれば、そこから表情の起点が作れる",
      zozoKeyword: "白シャツ",
    },
    avoidElements: ["大きなロゴ", "原色", "装飾的なプリント", "強い光沢"],
  },
  {
    id:   "refined-urban",
    name: "研ぎ澄まされた都市人",
    coreTags: ["clean", "structured", "refined", "mature"],
    psychologicalCore: "構造で伝える。隙のなさが安心の道具になっている。",
    clothingRole: "構造で自信を作り、清潔感で信頼を得る",
    avoidImpressions: ["着られている", "子どもっぽい", "清潔感がない"],
    idealSelf: "場の温度を上げる、構造で語る大人",
    colors: ["黒", "ネイビー", "ライトグレー", "白", "チャコール"],
    materials: ["上質ウール", "ハリのあるコットン", "レザー", "シルク混"],
    silhouettes: ["Iライン", "Yライン", "テーラード", "シャープなストレート"],
    accessories: ["ステンレスの時計", "細い革ベルト", "革靴"],
    brands: ["Theory", "Hyke", "Graphpaper", "Jil Sander", "Auralee"],
    music:    ["ミニマルテクノ", "ECM系ジャズ", "Nils Frahm"],
    films:    ["ミヒャエル・ハネケ", "トム・フォード", "デヴィッド・フィンチャー"],
    fragrance:["シダーウッド", "ベチバー", "レザー"],
    firstPiece: {
      name:        "黒のテーラードジャケット",
      why:         "構造の起点。これ一枚で立ち姿が変わる",
      zozoKeyword: "黒ジャケット",
    },
    avoidElements: ["派手なロゴ", "ダボついたシルエット", "安価な化繊光沢"],
  },
  {
    id:   "rebel-creator",
    name: "逸脱するクリエイター",
    coreTags: ["rebellious", "raw", "dark", "expressive"],
    psychologicalCore: "整いすぎたものへの抵抗。自分の視点を残して着る。",
    clothingRole: "既存のルールを壊し、自分の輪郭を作る",
    avoidImpressions: ["量産型", "無難", "まじめすぎ"],
    idealSelf: "違和感を残しながら自分の道を歩む人",
    colors: ["黒", "墨", "ダークブラウン", "生成り", "退色グレー"],
    materials: ["デニム", "レザー", "ヴィンテージウール", "ヘビー綿"],
    silhouettes: ["オーバーサイズ", "ワーク", "変則レイヤード", "崩れたシルエット"],
    accessories: ["ヴィンテージ時計", "革のラフなブレス", "シルバーリング"],
    brands: ["Yohji Yamamoto", "Comme des Garçons", "Number (N)ine", "Maison Margiela", "Needles"],
    music:    ["グランジ", "ポストパンク", "シューゲイザー"],
    films:    ["ジム・ジャームッシュ", "デヴィッド・リンチ", "ウォン・カーウァイ"],
    fragrance:["トバコ", "レザー", "インセンス"],
    firstPiece: {
      name:        "黒のロングコート",
      why:         "形ではなく思想を着る入口になる",
      zozoKeyword: "黒ロングコート",
    },
    avoidElements: ["量産プチプラ", "清潔感だけの服", "流行のコピー"],
  },
  {
    id:   "soft-intimate",
    name: "柔らかな親密性",
    coreTags: ["soft", "romantic", "approachable", "open"],
    psychologicalCore: "人との距離を近づける肌触りを選ぶ。重さを持たないことで信頼を作る。",
    clothingRole: "関係を柔らかくし、肌触りで自分の温度を伝える",
    avoidImpressions: ["怖い", "近寄りがたい", "堅すぎ"],
    idealSelf: "人を緊張させない、柔らかい光のような人",
    colors: ["アイボリー", "桜色", "ミルクティー", "ラベンダー", "淡いグレー"],
    materials: ["コットン", "やわらかニット", "起毛素材", "シフォン"],
    silhouettes: ["Aライン", "丸みのあるカーディガン", "ふんわりブラウス"],
    accessories: ["細いゴールド", "淡い色のバッグ", "布の靴"],
    brands: ["SNIDEL", "Mame Kurogouchi", "FRAY I.D", "Adam et Ropé", "TOMORROWLAND"],
    music:    ["ネオソウル", "ボサノバ", "シティポップ"],
    films:    ["是枝裕和", "新海誠", "グレタ・ガーウィグ"],
    fragrance:["ミュゲ", "ホワイトムスク", "ピオニー"],
    firstPiece: {
      name:        "オフホワイトのニット",
      why:         "肌触りで自分の温度を伝える1枚",
      zozoKeyword: "ホワイトニット",
    },
    avoidElements: ["攻撃的なロゴ", "重く硬い素材", "暗色だけの全身"],
  },
  {
    id:   "night-gravitas",
    name: "夜の余白",
    coreTags: ["dark", "sensual", "mysterious", "heavy"],
    psychologicalCore: "全部を見せない。沈黙と影で語る。",
    clothingRole: "影をまとい、語らない深さを作る",
    avoidImpressions: ["チャラい", "子どもっぽい", "軽い"],
    idealSelf: "言葉数の少ない、夜が似合う人",
    colors: ["黒", "墨", "深紫", "ボルドー", "チャコール"],
    materials: ["シルク", "ヴィスコース", "レザー", "サテン"],
    silhouettes: ["Iライン", "ロング", "ドレープ", "覆うシルエット"],
    accessories: ["シルバージュエリー", "薄手のスカーフ", "革小物"],
    brands: ["Ann Demeulemeester", "Rick Owens", "Yohji Yamamoto", "Maison Margiela", "Haider Ackermann"],
    music:    ["トリップホップ", "ダークアンビエント", "ネオクラシカル"],
    films:    ["ヌーヴェルヴァーグ", "ウォン・カーウァイ", "ラース・フォン・トリアー"],
    fragrance:["トバコ", "ウード", "インセンス"],
    firstPiece: {
      name:        "黒のドレープロングシャツ",
      why:         "影をまとう起点になる1枚",
      zozoKeyword: "黒ロングシャツ",
    },
    avoidElements: ["蛍光色", "明るすぎるカラー", "過度な装飾"],
  },
  {
    id:   "natural-editor",
    name: "自然体の編集者",
    coreTags: ["natural", "relaxed", "raw", "approachable"],
    psychologicalCore: "力みのない、選び抜いた日常。素材と空気感に敏感。",
    clothingRole: "自然な空気をつくり、リラックスを保つ",
    avoidImpressions: ["着られている", "わざとらしい", "攻撃的"],
    idealSelf: "力を抜いて、自分の空気を持っている人",
    colors: ["ベージュ", "カーキ", "生成り", "グレージュ", "ブラウン"],
    materials: ["リネン", "コットン", "ヴィンテージウール", "麻混"],
    silhouettes: ["ストレート", "ゆるやかな箱形", "ロング"],
    accessories: ["布のトート", "革のサンダル", "木のアクセ"],
    brands: ["Margaret Howell", "orSlow", "Engineered Garments", "Comoli", "ARTS&SCIENCE"],
    music:    ["フォーク", "ネオソウル", "アンビエントフォーク"],
    films:    ["是枝裕和", "アンドレア・アーノルド", "ケリー・ライカート"],
    fragrance:["ベチバー", "シダーウッド", "グリーン"],
    firstPiece: {
      name:        "リネンのプルオーバーシャツ",
      why:         "力みを抜いて空気をつくる一枚",
      zozoKeyword: "リネンシャツ",
    },
    avoidElements: ["派手な化繊", "過度な構造", "強いブランドロゴ"],
  },
  {
    id:   "futuristic-minimalist",
    name: "未来的ミニマリスト",
    coreTags: ["futuristic", "minimal", "clean", "sharp"],
    psychologicalCore: "余分を削ぐ。線と機能で美を作る。",
    clothingRole: "余白を作り、機能で語る",
    avoidImpressions: ["古くさい", "装飾的", "ダサい"],
    idealSelf: "余白を持って未来側を向いて立つ人",
    colors: ["白", "ライトグレー", "シルバー", "黒", "ブルーグレー"],
    materials: ["テックナイロン", "テンセル", "リサイクル素材", "シャープウール"],
    silhouettes: ["Iライン", "シャープ", "ボックス", "テック系オーバーサイズ"],
    accessories: ["テックウォッチ", "ミニマルバッグ", "白スニーカー"],
    brands: ["TEATORA", "nanamica", "GOLDWIN", "COS", "Y-3"],
    music:    ["アンビエントテクノ", "IDM", "Bicep"],
    films:    ["Drive", "Ex Machina", "Her"],
    fragrance:["メタリック", "オゾン", "ホワイトシダー"],
    firstPiece: {
      name:        "テック素材のシャープなコート",
      why:         "未来側に立つための起点",
      zozoKeyword: "テックコート",
    },
    avoidElements: ["強いカラー", "装飾", "ヴィンテージ感"],
  },
  {
    id:   "expressive-light",
    name: "軽やかな表現者",
    coreTags: ["expressive", "youthful", "light", "open"],
    psychologicalCore: "重さを持たず、色や柄で気分を表現する。今を楽しむ。",
    clothingRole: "気分を上げ、自分の今を表現する",
    avoidImpressions: ["暗い", "地味", "堅い"],
    idealSelf: "軽やかに、今の自分を楽しむ人",
    colors: ["パステル", "鮮やかな赤", "鮮やかな青", "白", "淡いミント"],
    materials: ["コットン", "軽いポリ", "シフォン", "薄手のニット"],
    silhouettes: ["ふんわり", "ショート丈", "Aライン"],
    accessories: ["カラフルバッグ", "スニーカー", "軽いキャップ"],
    brands: ["BEAMS", "niko and...", "Adam et Ropé", "FREAK'S STORE", "BAYFLOW"],
    music:    ["シティポップ", "Kポップ", "インディポップ"],
    films:    ["ウェス・アンダーソン", "グレタ・ガーウィグ", "リチャード・リンクレイター"],
    fragrance:["シトラス", "フルーティ", "フローラル"],
    firstPiece: {
      name:        "明るい色のショート丈ジャケット",
      why:         "気分を上げる軽い1枚",
      zozoKeyword: "ショートジャケット",
    },
    avoidElements: ["全身ダーク", "過度な構造", "重く硬い素材"],
  },
];

export function getPatternById(id: string): WorldviewPattern | undefined {
  return WORLDVIEW_PATTERNS.find((p) => p.id === id);
}
